# =========================================================================
# KITTY CONFIG - WINE & BLACK EDITION
# =========================================================================

# --- Tipografía ---
font_family      JetBrains Mono Medium
bold_font        JetBrains Mono Bold
italic_font      JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic
font_size        11.0

# --- Ventana y Bordes ---
window_padding_width 12
background_opacity 0.94
hide_window_decorations yes

# --- Cursor ---
cursor_shape block
cursor_blink_interval 0.5

# --- Paleta de Colores: Negro y Rojo Vino ---
background #0a0a0a
foreground #e0e0e0

# Colores normales
color0  #161616
color1  #b22222
color2  #722F37
color3  #a53842
color4  #3d5672
color5  #803348
color6  #5c8296
color7  #e0e0e0

# Colores brillantes (Intensos)
color8  #2a2a2a
color9  #ff4d4d
color10 #993d48
color11 #cc4452
color12 #517296
color13 #a6435c
color14 #78a8c2
color15 #ffffff

# Selección de texto
selection_background #722F37
selection_foreground #ffffff
